# Generated by Django 2.2.3 on 2019-07-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_userprofileinfo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('email', models.CharField(max_length=96)),
                ('phone', models.CharField(max_length=96)),
                ('city', models.CharField(max_length=96)),
                ('content', models.TextField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
