# Generated by Django 2.2.3 on 2019-07-19 02:46

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0005_auto_20190719_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
