# Generated by Django 2.2.3 on 2019-07-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0007_auto_20190719_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
