# Generated by Django 2.2.3 on 2019-07-19 22:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0008_auto_20190719_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='content',
        ),
        migrations.AddField(
            model_name='person',
            name='query',
            field=models.CharField(default=datetime.datetime(2019, 7, 19, 22, 41, 56, 517139, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
