# Generated by Django 2.2.3 on 2019-07-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0009_auto_20190720_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='query',
            field=models.TextField(default='I am interested. Please call on XXXXXXXXXX', max_length=300),
        ),
    ]
